
### 게시글 좋아요
POST http://localhost:8080/boards/1/likes
Content-Type: application/json
Authorization: Bearer {{access_token}}

### 게시글 좋아요 취소
DELETE http://localhost:8080/boards/1/likes
Content-Type: application/json
Authorization: Bearer {{access_token}}

### 댓글 좋아요
POST http://localhost:8080/comments/1/likes
Content-Type: application/json
Authorization: Bearer {{access_token}}

### 댓글 좋아요 취소
DELETE http://localhost:8080/comments/1/likes
Content-Type: application/json
Authorization: Bearer {{access_token}}