### 인증메일전송
POST http://localhost:8080/users/email
Content-Type: application/json

{
  "email": "helloworld@gmail.com"
}

### 인증메일전송
POST http://localhost:8080/users/email
Content-Type: application/json

{
  "email": "helloworld2@gmail.com"
}

### 인증메일전송
POST http://localhost:8080/users/email
Content-Type: application/json

{
  "email": "helloworld3@gmail.com"
}

### 메일인증
PUT http://localhost:8080/users/email/verification
Content-Type: application/json

{
  "email": "helloworld@gmail.com",
  "code": ""
}