### 인증메일전송
POST http://localhost:8080/users/email
Content-Type: application/json

{
  "email": "helloworld6@gmail.com"
}

### 인증메일전송
POST http://localhost:8080/users/email
Content-Type: application/json

{
  "email": "dlskdud124@naver.com"
}

### 인증메일전송
POST http://localhost:8080/users/email
Content-Type: application/json

{
  "email": "dlskdud124@naver.com"
}

### 메일인증
PUT http://localhost:8080/users/email/verification
Content-Type: application/json

{
  "email": "helloworld6@gmail.com",
  "code": "PUOzRDzJ"
}