
### 회원가입
POST http://localhost:8080/users/signup
Content-Type: application/json

{
  "username" : "username",
  "password" : "passWord123!",
  "email": "helloworld6@gmail.com",
  "nickname": "nickname"
}

### 회원가입2
POST http://localhost:8080/users/signup
Content-Type: application/json

{
  "username" : "username4",
  "password": "pass1234!",
  "email": "helloworld4@gmail.com",
  "nickname": "nickname"
}

### 회원가입3
POST http://localhost:8080/users/signup
Content-Type: application/json

{
  "username": "dlskdud123",
  "password": "dlskdud123@",
  "email": "dlskdud123@gmail.com",
  "nickname": "code3line"
}

### ADMIN : 회원가입
POST http://localhost:8080/users/signup
Content-Type: application/json

{
  "username" : "dlskdud124",
  "password" : "dlskdud124@",
  "email" : "dlskdud124@naver.com",
  "nickname" : "두유",
  "admin" : "zhemtpwnfdpsmseoajflrkdlTek"

}

### ADMIN : 회원가입
POST http://localhost:8080/users/signup
Content-Type: application/json

{
  "username" : "username1",
  "password" : "password123!",
  "email" : "username@gmail.com",
  "nickname" : "관리자",
  "admin" : "zhemtpwnfdpsmseoajflrkdlTek"

}
