### 회원가입
POST http://localhost:8080/users/signup
Content-Type: application/json

{
  "username" : "username6",
  "password" : "passWord1236!",
  "email": "helloworld6@gmail.com",
  "nickname": "nickname"
}

### 회원가입2
POST http://localhost:8080/users/signup
Content-Type: application/json

{
  "username" : "username4",
  "email": "helloworld4@gmail.com",
  "nickname": "nickname",
  "password": "pass1234!"
}

### 회원가입3
POST http://localhost:8080/users/signup
Content-Type: application/json

{
  "email": "helloworld3@gmail.com",
  "username": "name3",
  "password": "pass1234!"
}

### 회원가입4
POST http://localhost:8080/users/signup
Content-Type: application/json

{
  "username" : "dlskdud124",
  "password" : "dlskdud124@",
  "email" : "dlskdud124@naver.com",
  "nickname" : "두유",
  "admin" : "zhemtpwnfdpsmseoajflrkdlTek"

}
